name: CI
on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ptgladk
  REPO: ptgladk/testrepo
  TAG: 'v1.0.0-alpha'

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REPO }}:latest,${{ env.REPO }}:${{ env.TAG }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.github_token }}
          tag: ${{ steps.versioning.outputs.version }}
          name: ${{ steps.versioning.outputs.version }}
          prerelease: true
          allowUpdates: true
