name: test

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Set tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/heads/release/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.tag.outputs.tag }}
        run: |
          echo $GITHUB_REF
          echo $RELEASE_VERSION
          echo ${{ steps.tag.outputs.tag }}
          
  smoke:
    name: Build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs.tag }}
    
