name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - run: echo ${GITHUB_REF}
      - run: echo ${GITHUB_HEAD_REF}
      - run: echo ${GITHUB_SHA}
      - uses: actions/checkout@v3
      - run: cat README.md

#      - name: Set tag
#        id: tag
#        run: echo ::set-output name=tag::${GITHUB_REF#refs/heads/release/}
      - name: Set tag
        id: tag
        run: |
          if [[ "${{ github.head_ref }}" =~ ^release/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=tag::${GITHUB_HEAD_REF#release/}-something
          elif [[ ${{ github.ref }} =~ ^refs/heads/develop$ ]]; then
              echo ::set-output name=tag::develop
          elif [[ ${{ github.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
          fi
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.tag.outputs.tag }}
        run: |
          echo $GITHUB_REF
          echo $RELEASE_VERSION
          echo ${{ steps.tag.outputs.tag }}
          
  smoke:
    name: Build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs.tag }}
    
