name: test

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

#      - name: Set tag
#        id: tag
#        run: echo ::set-output name=tag::${GITHUB_REF#refs/heads/release/}
      - name: Set tag
        id: tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs/heads/release/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=tag::${GITHUB_REF#refs/heads/release/}
          elif [[ ${{ github.ref }} =~ ^refs/heads/develop$ ]]; then
              echo ::set-output name=tag::develop
          elif [[ ${{ github.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
          fi
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.tag.outputs.tag }}
        run: |
          echo $GITHUB_REF
          echo $RELEASE_VERSION
          echo ${{ steps.tag.outputs.tag }}
          
  smoke:
    name: Build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs.tag }}
    
